// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV4cW9G86XWJ__7e-6JHWpXvR33bTfCso',
    appId: '1:727983529777:web:0930d1e9ea7b2ce7fc9a10',
    messagingSenderId: '727983529777',
    projectId: 'a-flutterdemo',
    authDomain: 'a-flutterdemo.firebaseapp.com',
    storageBucket: 'a-flutterdemo.firebasestorage.app',
    measurementId: 'G-X2D5FKJY3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsRJtZmmlTqi2xWLNzpZHjuVZGTrsjas',
    appId: '1:727983529777:android:64603664a91c1a40fc9a10',
    messagingSenderId: '727983529777',
    projectId: 'a-flutterdemo',
    storageBucket: 'a-flutterdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4eNQrYFEuDiwc90PgqBuCKGkJawUHtgI',
    appId: '1:727983529777:ios:6b42c225ba387e61fc9a10',
    messagingSenderId: '727983529777',
    projectId: 'a-flutterdemo',
    storageBucket: 'a-flutterdemo.firebasestorage.app',
    iosBundleId: 'amanda.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4eNQrYFEuDiwc90PgqBuCKGkJawUHtgI',
    appId: '1:727983529777:ios:96151db574a84ccafc9a10',
    messagingSenderId: '727983529777',
    projectId: 'a-flutterdemo',
    storageBucket: 'a-flutterdemo.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV4cW9G86XWJ__7e-6JHWpXvR33bTfCso',
    appId: '1:727983529777:web:dad05269afb8287efc9a10',
    messagingSenderId: '727983529777',
    projectId: 'a-flutterdemo',
    authDomain: 'a-flutterdemo.firebaseapp.com',
    storageBucket: 'a-flutterdemo.firebasestorage.app',
    measurementId: 'G-JHRBBQHFS2',
  );

}